import bcrypt from 'bcryptjs';

const data = {

  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    } 
  ],

  products: [
    {
      name: "Mini Focus Watch",
      slug: "hand-watch",
      category: "Watches",
      image: "/images/mini-focus-blue.jpg",
      price: 220,
      brand: "Mini Focus",
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
      description: "A modern high quality watch",
    },
    {
      name: "Mini Focus Blue Quartz",
      slug: "mini-focus-blue-quartz",
      category: "Watches",
      image: "/images/mini-focus-blue-quartz.jpg",
      price: 260,
      brand: "Mini Focus",
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
      description: "A modern high quality quartz watch",
    },
    {
      name: "iPhone 11",
      slug: "iphone-11",
      category: "Phones",
      image: "/images/iphone-11-green.jpg",
      price: 2850,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "iPhone 11, 128 GB, Green",
    },
    {
      name: "iPhone 12 Red",
      slug: "iphone-12-red",
      category: "Phones",
      image: "/images/iphone-12-red.jpg",
      price: 3900,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A relaxing Shirt with nice looks",
    },
    {
      name: "iPhone 12 Green",
      slug: "iphone-12-green",
      category: "Phones",
      image: "/images/iphone-12-green.jpg",
      price: 3950,
      brand: "Xiaomi",
      rating: 4.0,
      numReviews: 20,
      countInStock: 20,
      description: "iPhone 12 Green, 256 GB",
    },
    {
      name: "iPhone 11 Pro",
      slug: "iphone-11-pro",
      category: "Phones",
      image: "/images/iphone-11-pro.jpg",
      price: 2850,
      brand: "Nokia",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "iPhone 11 Pro, 128 GB",
    },
    {
      name: "iPhone 11 Blue",
      slug: "iphone-11-blue",
      category: "Phones",
      image: "/images/iphone-11-blue.jpg",
      price: 2850,
      brand: "Apple",
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: "iPhone 11 pro, Blue, 256 GB",
    },
    {
      name: "iPhone 12 Pro Max",
      slug: "iphone-12",
      category: "Watches",
      image: "/images/iphone-12-gold.jpg",
      price: 3550,
      brand: "Apple",
      rating: 4.0,
      numReviews: 10,
      countInStock: 10,
      description: "iPhone 12 Pro Max, Gold, 128 GB",
    },
  ],
};

export default data;